/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsLimitsRouteImport } from './routes/settings.limits'
import { Route as FormsMembershipUpdatesIndexRouteImport } from './routes/forms.membership-updates.index'
import { Route as FormsMembershipUpdatesSubmissionIdRouteImport } from './routes/forms.membership-updates.$submissionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLimitsRoute = SettingsLimitsRouteImport.update({
  id: '/settings/limits',
  path: '/settings/limits',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsMembershipUpdatesIndexRoute =
  FormsMembershipUpdatesIndexRouteImport.update({
    id: '/forms/membership-updates/',
    path: '/forms/membership-updates/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FormsMembershipUpdatesSubmissionIdRoute =
  FormsMembershipUpdatesSubmissionIdRouteImport.update({
    id: '/forms/membership-updates/$submissionId',
    path: '/forms/membership-updates/$submissionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/transactions': typeof TransactionsRoute
  '/settings/limits': typeof SettingsLimitsRoute
  '/settings/': typeof SettingsIndexRoute
  '/forms/membership-updates/$submissionId': typeof FormsMembershipUpdatesSubmissionIdRoute
  '/forms/membership-updates/': typeof FormsMembershipUpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/transactions': typeof TransactionsRoute
  '/settings/limits': typeof SettingsLimitsRoute
  '/settings': typeof SettingsIndexRoute
  '/forms/membership-updates/$submissionId': typeof FormsMembershipUpdatesSubmissionIdRoute
  '/forms/membership-updates': typeof FormsMembershipUpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/transactions': typeof TransactionsRoute
  '/settings/limits': typeof SettingsLimitsRoute
  '/settings/': typeof SettingsIndexRoute
  '/forms/membership-updates/$submissionId': typeof FormsMembershipUpdatesSubmissionIdRoute
  '/forms/membership-updates/': typeof FormsMembershipUpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/transactions'
    | '/settings/limits'
    | '/settings/'
    | '/forms/membership-updates/$submissionId'
    | '/forms/membership-updates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/transactions'
    | '/settings/limits'
    | '/settings'
    | '/forms/membership-updates/$submissionId'
    | '/forms/membership-updates'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/transactions'
    | '/settings/limits'
    | '/settings/'
    | '/forms/membership-updates/$submissionId'
    | '/forms/membership-updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  TransactionsRoute: typeof TransactionsRoute
  SettingsLimitsRoute: typeof SettingsLimitsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  FormsMembershipUpdatesSubmissionIdRoute: typeof FormsMembershipUpdatesSubmissionIdRoute
  FormsMembershipUpdatesIndexRoute: typeof FormsMembershipUpdatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/limits': {
      id: '/settings/limits'
      path: '/settings/limits'
      fullPath: '/settings/limits'
      preLoaderRoute: typeof SettingsLimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/membership-updates/': {
      id: '/forms/membership-updates/'
      path: '/forms/membership-updates'
      fullPath: '/forms/membership-updates/'
      preLoaderRoute: typeof FormsMembershipUpdatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/membership-updates/$submissionId': {
      id: '/forms/membership-updates/$submissionId'
      path: '/forms/membership-updates/$submissionId'
      fullPath: '/forms/membership-updates/$submissionId'
      preLoaderRoute: typeof FormsMembershipUpdatesSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  TransactionsRoute: TransactionsRoute,
  SettingsLimitsRoute: SettingsLimitsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  FormsMembershipUpdatesSubmissionIdRoute:
    FormsMembershipUpdatesSubmissionIdRoute,
  FormsMembershipUpdatesIndexRoute: FormsMembershipUpdatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
