/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsLimitsRouteImport } from './routes/settings.limits'
import { Route as FormsContactIndexRouteImport } from './routes/forms.contact.index'
import { Route as FormsContactSubmissionIdRouteImport } from './routes/forms.contact.$submissionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLimitsRoute = SettingsLimitsRouteImport.update({
  id: '/settings/limits',
  path: '/settings/limits',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsContactIndexRoute = FormsContactIndexRouteImport.update({
  id: '/forms/contact/',
  path: '/forms/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsContactSubmissionIdRoute =
  FormsContactSubmissionIdRouteImport.update({
    id: '/forms/contact/$submissionId',
    path: '/forms/contact/$submissionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/transactions': typeof TransactionsRoute
  '/settings/limits': typeof SettingsLimitsRoute
  '/settings/': typeof SettingsIndexRoute
  '/forms/contact/$submissionId': typeof FormsContactSubmissionIdRoute
  '/forms/contact/': typeof FormsContactIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/transactions': typeof TransactionsRoute
  '/settings/limits': typeof SettingsLimitsRoute
  '/settings': typeof SettingsIndexRoute
  '/forms/contact/$submissionId': typeof FormsContactSubmissionIdRoute
  '/forms/contact': typeof FormsContactIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/transactions': typeof TransactionsRoute
  '/settings/limits': typeof SettingsLimitsRoute
  '/settings/': typeof SettingsIndexRoute
  '/forms/contact/$submissionId': typeof FormsContactSubmissionIdRoute
  '/forms/contact/': typeof FormsContactIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/transactions'
    | '/settings/limits'
    | '/settings/'
    | '/forms/contact/$submissionId'
    | '/forms/contact/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/transactions'
    | '/settings/limits'
    | '/settings'
    | '/forms/contact/$submissionId'
    | '/forms/contact'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/transactions'
    | '/settings/limits'
    | '/settings/'
    | '/forms/contact/$submissionId'
    | '/forms/contact/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  TransactionsRoute: typeof TransactionsRoute
  SettingsLimitsRoute: typeof SettingsLimitsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  FormsContactSubmissionIdRoute: typeof FormsContactSubmissionIdRoute
  FormsContactIndexRoute: typeof FormsContactIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/limits': {
      id: '/settings/limits'
      path: '/settings/limits'
      fullPath: '/settings/limits'
      preLoaderRoute: typeof SettingsLimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/contact/': {
      id: '/forms/contact/'
      path: '/forms/contact'
      fullPath: '/forms/contact/'
      preLoaderRoute: typeof FormsContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/contact/$submissionId': {
      id: '/forms/contact/$submissionId'
      path: '/forms/contact/$submissionId'
      fullPath: '/forms/contact/$submissionId'
      preLoaderRoute: typeof FormsContactSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  TransactionsRoute: TransactionsRoute,
  SettingsLimitsRoute: SettingsLimitsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  FormsContactSubmissionIdRoute: FormsContactSubmissionIdRoute,
  FormsContactIndexRoute: FormsContactIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
